language: cpp
sudo: required
dist: trusty
services: [docker]

os:
  - linux
#  - osx

# Define clang compiler without any frills
compiler:
  - clang
  - gcc

env:
  - CONFIG=Release ASAN_OPTIONS=detect_odr_violation=1:leak_check_at_exit=0
  - CONFIG=Debug ASAN_OPTIONS=detect_odr_violation=1:leak_check_at_exit=0

git:
  depth: 3

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker build -t keepassxc/travis - < TravisDockerfile; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew ls | grep -wq cmake || brew install cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew ls | grep -wq qt5 || brew install qt5; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew ls | grep -wq libgcrypt || brew install libgcrypt; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mkdir build && pushd build; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker run -v $PWD:/keepassxc/src:ro -w /keepassxc/build
        -e "CC=$CC" -e "CXX=$CXX" -e "ASAN_OPTIONS=$ASAN_OPTIONS" -e "CONFIG=$CONFIG"
        keepassxc/travis;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake -DCMAKE_BUILD_TYPE=${CONFIG} -DWITH_GUI_TESTS=ON -DWITH_ASAN=ON -DWITH_XC_HTTP=ON -DWITH_XC_AUTOTYPE=ON -DWITH_XC_YUBIKEY=ON $CMAKE_ARGS ..; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make -j2; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make test ARGS+="--output-on-failure"; fi

# Generate snapcraft build when merging into master/develop branches
#after_success:
#  - popd
#  - "[[ $DEPLOY = 1 ]] && [[ $CONFIG = Release ]] && [[ $TRAVIS_BRANCH =~ (master|develop) ]] && [[ $TRAVIS_PULL_REQUEST = false ]] \
#    && docker run -v $(pwd):/cwd snapcore/snapcraft sh -c 'cd /cwd && apt update && snapcraft'"
