# TIP: validate this file using http://lint.travis-ci.org

dist: trusty

# FIXME : remove when (https://github.com/google/sanitizers/issues/837) is resolved.
group: deprecated-2017Q3

language: cpp

sudo: required

env:
  global:
    - ASAN_OPTIONS=detect_odr_violation=1:leak_check_at_exit=0

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      env: CONFIG=Debug
    - os: linux
      compiler: clang
      env: CONFIG=Debug
    - os: linux
      compiler: gcc
      env: CONFIG=Release
    - os: linux
      compiler: clang
      env: CONFIG=Release
    - os: linux
      compiler: clang
      env: CONFIG=Debug DOCKER_IMG=debian
    - os: linux
      compiler: gcc
      env: CONFIG=Release DOCKER_IMG=ubuntu
    - os: osx
      compiler: clang
      env: CONFIG=Debug
  allow_failures:
    - os: linux
      compiler: clang
      env: CONFIG=Debug DOCKER_IMG=debian
    - os: linux
      compiler: gcc
      env: CONFIG=Release DOCKER_IMG=ubuntu
    - os: osx
      compiler: clang
      env: CONFIG=Debug

git:
  depth: 3

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ] && [ -z "${DOCKER_IMG}"]; then
      sh -c "ci/travis-install.sh";
    fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ] && [ ! -z "${DOCKER_IMG}" ]; then
      sudo service docker start;
      unset TRAVIS_COMMIT_MESSAGE; printenv > /tmp/build.env;
      sh -c "ci/travis-install-docker.sh";
      export DOCKER_CMD="docker run --rm --env-file /tmp/build.env -v ${PWD}:/keepassxc ${DOCKER_USER}/keepassxc:${DOCKER_IMG}-${CONFIG} /bin/sh -c";
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      sh -c "ci/travis-install-mac.sh";
      sh -c "ci/travis-install-mac-libqhttpengine.sh";
      sh -c "ci/travis-install-mac-kf5archive.sh";
    fi

before_script:
  - mkdir build;

script:
  - sh -c "${DOCKER_CMD} ci/travis-build.sh";
  - sh -c "${DOCKER_CMD} ci/travis-test.sh";

after_success:
  - sh -c "ci/travis-after_success.sh";
