name: keepassxc
adopt-info: keepassxc
grade: stable
base: core18
confinement: strict
compression: lzo

apps:
  keepassxc:
    command: keepassxc
    common-id: org.keepassxc.KeePassXC.desktop
    extensions: [kde-neon]
    plugs: [kde-frameworks-5-plug, home, unity7, network, network-bind, removable-media, raw-usb]
  cli:
    command: keepassxc-cli
    extensions: [kde-neon]
    plugs: [home, removable-media, raw-usb]
  proxy:
    command: keepassxc-proxy
    extensions: [kde-neon]
    plugs: [home]
    
slots:
  session-dbus-interface:
    interface: dbus
    name: org.keepassxc.KeePassXC.MainWindow
    bus: session

parts:
  keepassxc:
    source: .
    plugin: cmake
    parse-info: [usr/share/metainfo/org.keepassxc.KeePassXC.appdata.xml]
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DKEEPASSXC_DIST_TYPE=Snap
      - -DKEEPASSXC_BUILD_TYPE=Release
      - -DWITH_TESTS=OFF
      - -DWITH_XC_ALL=ON
    build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
    build-packages:
      - g++
      - libbotan-2-dev
      - libqt5x11extras5-dev
      - libqt5svg5-dev
      - qtbase5-private-dev
      - qttools5-dev
      - qttools5-dev-tools
      - zlib1g-dev
      - libxi-dev
      - libxtst-dev
      - libqrencode-dev
      - libusb-1.0-0-dev
      - libminizip-dev
      - asciidoctor
    stage-packages:
      - dbus
      - botan
      - libxtst6
      - libqt5x11extras5
      - libqt5svg5
      - libqt5concurrent5
      - libqrencode3
      - libusb-1.0-0
      - xclip
